spring:
  threads:
    virtual:
      enabled: true
  zipkin:
    base-url: http://zipkin:9411  # URL of your Zipkin server

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
#  zipkin:
#    tracing:
#      endpoint: ${BASE_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,refresh