server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh