spring:
  task:
    execution:
      thread:
        executor:
          type: virtual  # Ensures the use of virtual threads
      thread-name-prefix: "virtual-thread-"
  zipkin:
    base-url: ${BASE_URL:http://localhost:9411}  # URL of your Zipkin server

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  tracing:
    probability: 1.0  # 100% of requests will be traced for a dev mode adjust for prod
  endpoints:
    web:
      exposure:
        include: health,refresh