server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://btb:btb@localhost:27017/customerDb?authSource=admin
#      host: localhost
#      database: customerDb  # The name of the database to connect to
#      username: btb  # MongoDB username (optional if included in URI)
#      password: btb  # MongoDB password (optional if included in URI)
#      port: 27017
#      authentication-database: admin