server:
  port: 8081

spring:
  data:
    mongodb:
#      uri: mongodb://btb:btb@mongo:27017/customerDb?authSource=admin
      host: ${DB_HOST:localhost}
      database: ${DB_DATABASE:customerDb}  # The name of the database to connect to
      username: ${DB_USERNAME:btb}  # MongoDB username (optional if included in URI)
      password: ${DB_PASSWORD:btb}  # MongoDB password (optional if included in URI)
      port: ${DB_PORT:27017}
      authentication-database: admin