spring:
  data:
    mongodb:
      host: localhost
      database: test_customerDb
      username: btb
      password: btb
      port: 27017
      authentication-database: admin


 # Embedded MongoDB settings (Flapdoodle)
#  mongodb.embedded.version: 4.0.2