server:
  port: 8085

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      database: ${DB_DATABASE:notificationDb}  # The name of the database to connect to
      username: ${DB_USERNAME:btb}  # MongoDB username (optional if included in URI)
      password: ${DB_PASSWORD:btb}  # MongoDB password (optional if included in URI)
      port: ${DB_PORT:27017}
      authentication-database: admin

  kafka:
    bootstrap-servers: kafka:9092
    group-id: paymentGroup, orderGroup
    auto-offset-reset: earliest
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.damlotec.ecommerce.kafka.order.OrderConfirmation,paymentNotification:com.damlotec.ecommerce.kafka.payment.PaymentNotification

  mail:
    host: maildev
