server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceorder
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.damlotec.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8081/api/v1/customers
    product-url: http://localhost:8082/api/v1/products
    payment-url: http://localhost:8080/api/v1/payments
