server:
  port: 8087

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ecommercepayment}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        schema.registry.url: http://schema-registry:8088
#        spring.json.type.mapping: paymentNotification:com.avro.PaymentNotification

logging:
  level:
    org.apache.kafka: DEBUG
    io.confluent.kafka: DEBUG
