server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Use none or validate if using Flyway for schema management
    show-sql: true  # Displays SQL queries in the console
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration  # Path where migration scripts are located
    baseline-on-migrate: true  # Ensures Flyway starts with a baseline
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
